CREATE TABLE IF NOT EXISTS inventario (
    producto_id BIGINT PRIMARY KEY,
    stock INT NOT NULL CHECK (stock >= 0)
);
CREATE TABLE IF NOT EXISTS clientes (
    id BIGINT PRIMARY KEY,
    tipo_cliente VARCHAR(30) NOT NULL,
    nit VARCHAR(30)
);
CREATE TABLE IF NOT EXISTS facturas (
    id BIGINT PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES clientes(id),
    monto DECIMAL(12, 2) NOT NULL,
    pagada BOOLEAN NOT NULL
);
CREATE TABLE IF NOT EXISTS pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES clientes(id),
    subtotal DECIMAL(12, 2) NOT NULL,
    descuento DECIMAL(12, 2) NOT NULL,
    impuesto DECIMAL(12, 2) NOT NULL,
    total DECIMAL(12, 2) NOT NULL,
    fecha TIMESTAMP NOT NULL,
    estado VARCHAR(30) NOT NULL
);
CREATE TABLE IF NOT EXISTS detalle_pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL REFERENCES pedidos(id),
    producto_id BIGINT NOT NULL REFERENCES inventario(producto_id),
    cantidad INT NOT NULL CHECK (cantidad > 0)
);